language: node_js
node_js:
  - "22"

cache:
  directories:
    - "node_modules"

branches:
  only:
    - develop

env:
  global:
    - NEXT_PUBLIC_GITHUB_USERNAME=lon9

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: master
  local-dir: out
  on:
    branch: develop
